project:
  title: "geostat_tutorial"
  output-dir: "./docs"
  execute-dir: project
  

editor: visual

number-sections: false
highlight-style: tango
theme: [yeti, theme.scss]
css: style.css
code-block-bg: true
code-block-border-left: "#7AB629"

format: 
  html:
    mainfont: "calibri"
    code-fold: false
    smooth-scroll: true
    toc: true

webr: 
  show-startup-message: true    # Disable displaying status of webR initialization